<?php
$Headline = "WIKIGINI";
$Description = "WIKIGINI visualisiert die Ungleichheit der Autorenschaft in einem Wikipediaartikel: es werden die Autoren aller Wörter in jeder Revision eines Artikels ermittelt und der <a href=\"http://de.wikipedia.org/wiki/Gini-Koeffizient\">Gini-Index</a> als Maß für Ungleichheit berechnet. So kann gezeigt werden, ob die \"Autorenschaft\" der Wörter in einem Artikel sich von relativ gleich (z. B. jeder Autor hat in etwa die selbe Menge an Wörtern geschrieben) zu sehr ungleich (z. B. 2% der Autoren haben 90% der Wörter geschrieben) gewandelt hat.";

$MoreInfo = "Weitere Informationen";

?>