<?php
$Headline = "WIKIGINI";
$Description = "WIKIGINI visualisiert die Ungleichheit der Autorenschaft in einem Wikipediaartikel: es werden akkurat die Autoren aller Wörter in jeder Revision eines Articles ermittelt und der sogenannte \"Gini-Index\" als Ungleichheitsmesswert. Es kann so gezeigt werden, ob die \"Autorenschaft\" der Wörter in einem Artikel sich von relativ gleich (z.B. jeder Autor hat in etwa die selbe Menge an Wörtern geschrieben) zu sehr ungleich (z.B. 2% der Autoren haben 90% der Wörter geschrieben) verschoben hat.";

$MoreInfo = "Weitere Informationen";

?>