<?php
$Headline = "WikiGini";
$Description = "WikiGini untersucht und veranschaulicht die Verteilung 
	der Autorenschaft in einem Wikipedia-Artikel im zeitlichen Verlauf.
	<br /><br />
	Für jede Revision eines Artikels wird die Menge der Wörter ermittelt, 
	die jeder Autor geschrieben hat und damit der <a href=\"http://de.wikipedia.org/wiki/Gini-Koeffizient\">Gini-Index</a> als Maß für 
	Ungleichheit berechnet. Das Ergebnis wird in einem Diagramm dargestellt. 
	Daran lässt sich ablesen, ob die Autorenschaft in einem Artikel 
	gleichmäßig verteilt ist. Und man kann beobachten, wie sich die 
	Verteilung im Zeitverlauf verändert. Ob sie sich zum Beispiel von 
	relativ gleich (jeder Autor hat in etwa die gleiche Menge an Wörtern 
	geschrieben) zu sehr ungleich (wenige Autoren haben einen Großteil 
	der Wörter geschrieben) gewandelt hat.";
$Headline2 = "Beispiel";
$Description2 = "Im Beispiel sieht man das Diagramm zu dem Wikipedia-Artikel 
	über Barack Obama. Der Gini-Index kann sich zwischen 0 und 1 bewegen. 
	Je niedriger der Wert, desto gleichmäßiger die Verteilung der 
	Autorenschaft (0 = jeder Autor hat die gleiche Menge an Wörtern 
	geschrieben), je höher der Wert, desto ungleicher die Verteilung 
	(1 = ein Autor hat alles geschrieben).<br /><br />
	Mithilfe der Schaltflächen unterhalb des Diagramms kann man zwischen 
	einer Anzeige des Datums oder der einzelnen Revisionen auf der 
	Zeitachse wechseln, sowie vor- und zurückblättern. Wenn man die Maus 
	über die Grafik bewegt, erscheinen in einem kleinen Fenster die 
	Details zur jeweiligen Revision / dem jeweiligen Datum. Die Grafik 
	lässt sich vergrößern, indem man einen bestimmten Bereich mit der 
	Maus markiert.";

$MoreInfo = "Weitere Informationen";
$txtGraphHeader1 = "WikiGini - Artikel ";
$txtGraphHeader2 = " in der Sprache ";
$txtSwitchRevision = "Zum Revisionsmodus wechseln";
$txtSwitchTime = "Zum Datumsmodus wechseln";
?>
