<?php
$Headline = "Wikipedia Map Interface";
$Description = "Wikipedia Map ist Showcase in dem alle geogetaggter Artikel in Wikipedia visualisiert werden. Jeder geogetaggte Artikel wird durch eine Markierung an den entsprechenden Koordinaten dargestellt. Daraus entsteht eine Weltkarte aus Geotags.";

$MoreInfo = "Weitere Informationen";

$Languages["English"] = "Englisch";
$Languages["Catalan"] = "Katalan";
$Languages["Spanish"] = "Spanisch";
$Languages["Portuguese"] = "Portugisisch";
$Languages["French"] = "Französisch";
$Languages["Italian"] = "Italienisch";
$Languages["Greek"] = "Griechisch";
$Languages["Hebrew"] = "Hebräisch";
$Languages["Croatian"] = "Kroatisch";
$Languages["Turkish"] = "Türkisch";
$Languages["Russian"] = "Russisch";
$Languages["Chinese"] = "Chinesisch";

$DynamicMap["Headline"] = "Dynamische Karte";
$DynamicMap["Text"] = "
Die dynamische wird komplett im Browser erstellt. Dies hat den Vorteil, 
dass die Karte interaktiv ist, es kann z.B. in die Karte gezoomt werden, 
die Farben geändert werden und für jeden Punkt der entsprechende Artikel anzeigt werden.
Der Nachteil liegt im Resourcenverbraucht. <strong>Dieser Link kann den Browser abstürzen lassen!</strong>
Ein vergleichbar schneller Computer, eine aktuelle Version von Chrome und Gedult beim Laden sind nötig; 
der Browser läd mehr als 50MB Daten und verarbeitet diese mittels JavaScript in HTML5-Canvas. 
Die Karte kann lokal abgespeichert werden und kann dann ohne das Nachladen der Daten gestartet werden.";
?>
