<?php
$Headline = "Wikipedia Map Interface";
$Description = "Wikipedia Map ist Showcase in dem alle geogetaggter Artikel in Wikipedia visualisiert werden. Jeder geogetaggte Artikel wird durch eine Markierung an den entsprechenden Koordinaten dargestellt. Daraus entsteht eine Weltkarte aus Geotags.";

$MoreInfo = "Weitere Informationen";

$Languages["English"] = "Englisch";
$Languages["Catalan"] = "Katalan";
$Languages["Spanish"] = "Spanisch";
$Languages["Portuguese"] = "Portugisisch";
$Languages["French"] = "Französisch";
$Languages["Italian"] = "Italienisch";
$Languages["Greek"] = "Griechisch";
$Languages["Hebrew"] = "Hebräisch";
$Languages["Croatian"] = "Kroatisch";
$Languages["Turkish"] = "Türkisch";
$Languages["Russian"] = "Russisch";
$Languages["Chinese"] = "Chinesisch";

$DynamicMap["Headline"] = "Dynamische Karte";
$DynamicMap["Text"] = "
Die interaktive Karte wird dynamisch im Browser erstellt. So kann z. B. in die Karte gezoomt werden, die Farben geändert und für jeden Punkt der entsprechende Artikel anzeigt werden.
Ein Nachteil liegt im Resourcenverbrauch. <strong>Dieser Link kann den Browser abstürzen lassen!</strong>
Ein vergleichsweise schneller Computer, eine aktuelle Version von Chrome und Geduld beim Laden sind nötig. Der Browser lädt mehr als 50MB und verarbeitet diese mittels JavaScript in HTML5-Canvas. Die Karte kann lokal abgespeichert werden und dann ohne das Nachladen der Daten gestartet werden.";
?>
