<?php
$Headline = "Wikipedia Map";
$Introduction = "Wikipedia Map ist eine Visualisierung geogetaggter Artikel in Wikipedia. Jeder geogetaggte Artikel wird durch eine Markierung an den entsprechenden Koordinaten dargestellt. Daraus entsteht eine Weltkarte aus Geotags. ";

$Settings["Headline"] = "Einstellungen";
$Settings["Text"] = "Die darzustellende Sprachversion wird vom Nutzer ausgewählt. Mit der dynamischen Karte ist das Ein- und Auszoomen möglich. Außerdem können die geogetaggten Artikel angeklickt werden. ";

$Results["Headline"] = "Ergebnisse";
$Results["Text"] = "Die zu Grunde liegenden Daten werden von DBpedia extrahiert, welche Daten aus Wikipedia getrennt für jede unterstützte Sprache erhält. Es werden statisch generierte Bilder und eine dynamische Fassung angeboten, die Navigation und Zoomen erlaubt. Im Gegensatz zu Corpex, was ebenfalls Korpora und Sprachmodelle anbietet, ist die Wikipedia Map ein reines Visualisierungs-Tool. Nichtsdestotrotz stellt es eine wertvolle Informationsquelle über die Diversität von Wikipedia dar. ";

$Uses["Headline"] ="Nutzen";
$Uses["Text"] = "Einerseits werden offensichtliche Fehler aufgedeckt, beispielsweise befinden sich viele Artikel in französischer Sprache um den Nullmeridian herum. Andererseits wird ein vorhandener sprachspezifischer Bias sichtbar. Beispielsweise deckt die katalanische Wikipedia Katalonien in Spanien besonders gut ab. Sie deckt ebenfalls einige Teile Europas und der Vereinigten Staaten ab, aber es gibt nur eine schwache Abdeckung anderer Teile der Welt. Zukünftige Verbesserungen des Wikipedia Map Interface werden die Anstrengungen von Wikimedia widerspiegeln, bessere Unterstützung für die Extraktion geographischer Information anzubieten. ";


?>
