<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>RENDER | <?php echo $this->translate( "pageHeading", "common" ); ?> | <?php echo $this->translate( "articleMonitorHeading" ); ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		
		<link rel="stylesheet" type="text/css" href="<?php echo BASE_PATH; ?>res/css/alg_html.css" />
		<script type="text/javascript" src="<?php echo BASE_PATH; ?>res/js/jquery-1.8.0.min.js"></script>
	</head>

	<body>
		<div class="alg-container box-shadow">
<?php include( APP_PATH . "../templates/pageHeading.phtml" ); ?>

			<div style="padding-top: 10px;">
				<h2><?php echo $this->translate( "articleMonitorHeading" ); ?></h2>
				<p><?php echo $this->translate( "articleMonitorDesc" ); ?></p>
				<h4><?php echo $this->translate( "instHeading" ); ?></h4>
				<p><?php echo $this->translate( "instDesc" ); ?></p>
				<div class="box-shadow" style="padding-left: 20px;">
					<pre><code><?php
echo htmlentities("
var asqmReq = false;
var closeButton = \"<img border=\\\"0\\\" onclick=\\\"$('#asqmContainer').css('visibility', 'hidden')\\\" \" + 
  \"src=\\\"//upload.wikimedia.org/wikipedia/foundation/2/20/CloseWindow19x19.png\\\" \" + 
  \"style=\\\"position:absolute; right: 10px; cursor: pointer\\\">\";
 
if (wgNamespaceNumber == 0) {
  $('<li id=\"ca-asqm\" style=\"position: relative;\"><span><a onclick=\"javascript:asqm()\" ' + 
  'title=\"" . $this->translate("articleMonitorTooltip") . "\">" . $this->translate("articleMonitorTabTitle") . "</a></span>' + 
  '<div id=\"asqmContainer\" style=\"visibility: hidden; position:absolute; right: 0; ' +
  'font-size: 0.8em; border: 1px solid silver; margin: -5px 0 0 -1px; padding: 10px; ' +
  'z-index: 1000; background: white;\"></div></li>').insertAfter(\"#ca-history\");
}
 
function asqm() {
  if ($('#asqmContainer').css('visibility') == 'hidden') {
    $('#asqmContainer').css('visibility', 'visible');
    if (!asqmReq) {
      $('#asqmContainer').html('<img src=\"http://tools.wmflabs.org/" . str_replace( "local-", "", $this->getUserInfoObject( "name" ) ) . "/stools/res/img/load.gif\" style=\"padding: 20px;\" />');
      $.getJSON(\"http://tools.wmflabs.org/" . str_replace( "local-", "", $this->getUserInfoObject( "name" ) ) . "/stools/articleMonitor/query/json/id/\" + 
          wgArticleId + \"/lang/\" + wgContentLanguage + \"/asqmid/" . $this->getUniqueId() . "?callback=?\", function(data) {
        var output = \"<table>\";
        $.each(data.asqmResponse, function(key, groupObj) {
          output += \"<tr><td colspan='2' style='text-align: left; padding-top: 10px; font-weight: bold;'>\" + 
            groupObj.title + \"</td></tr>\";
          $.each(groupObj.items, function(itemTitle, value) {
            var link = \"\";
            if ($.isArray(value)) {
              if (value[0] === \"multipart\") {
                var val = \"\";
                $.each(value, function(index, part) {
                  if (index === 0) return true;
                  if ($.isArray(part)) {
                    link = part[1];
                    val += \"<a href='\" + link + \"' target='_blank' style='font-size: 1em; padding: 0; height: 1em;'>\" + 
                      part[0] + \"</a>\";
                  } else {
                    val += part;
                  }
                });
                value = val;
              } else {
                value = \"<a href='\" + value[1] + \"' target='_blank' style='font-size: 1em; padding: 0; height: 1em;'>\" + 
                  value[0] + \"</a>\";
              }
            }
            output += \"<tr><td style='padding-right: 10px;'>\" + itemTitle + \"</td><td>\" + value.toString() + \"</td></tr>\";
          });
        });
        output += \"</table>\";
        asqmReq = true;
        $('#asqmContainer').html(closeButton + output);
      });
    }
  } else {
    $('#asqmContainer').css('visibility', 'hidden');
  }
}
");
?></code></pre>
				</div>
				<h4><?php echo $this->translate( "noticeHeading" ); ?></h4>
				<p><?php echo $this->translate( "notice" ); ?></p>
			</div>
<?php require( 'disclaimer.phtml' ); ?>
		</div>
	</body>
</html>
