<?php $uName = $this->getUserInfoObject( "name" ); ?>
<?php SingletonFactory::getInstance( 'Asqm_Model' )->logRequest( $this->getTitle(), $this->getLanguage() ); ?>
<?php $callback = SingletonFactory::getInstance('Request')->getVar('callback'); ?>
<?php echo $callback; ?>({
	"asqmResponse": {
		"general": {
			"title": "<?php echo $this->translate( array( "groupStats", "title" ) ); ?>",
			"items": {
				"<?php echo $this->translate( array( "groupStats", "pageTitle" ) ); ?>": "<?php echo str_replace( '_', ' ', $this->getTitle() ); ?>",
<?php $articleStatus = SingletonFactory::getInstance( 'Api_Model' )->getFeaturedArticle( $this->getTitle() ); ?>
<?php if ( $articleStatus ): ?>
				"<?php echo $this->translate( array( "groupStats", "status" ) ); ?>": "<?php echo $articleStatus; ?>",
<?php endif; ?>
<?php $revInfo = $this->getRevisionInfo( true ); ?>
				"<?php echo $this->translate( array( "groupStats", "firstEdit" ) ); ?>": "<?php echo $this->getTimestamp( $revInfo[0]['rev_timestamp'] ); ?> (<?php echo $this->translate( array( "groupStats", "editedBy" ) ); ?> <?php echo $this->getRevisionUserName(); ?>)",
<?php $revInfo = $this->getRevisionInfo( false ); ?>
				"<?php echo $this->translate( array( "groupStats", "recentEdit" ) ); ?>": "<?php echo $this->getTimestamp( $revInfo[0]['rev_timestamp'] ); ?> (<?php echo $this->translate( array( "groupStats", "editedBy" ) ); ?> <?php echo $this->getRevisionUserName(); ?>)",
<?php $editorCount = $this->getUniqueEditorCount(); ?>
				"<?php echo $this->translate( array( "groupStats", "totalEditors" ) ); ?>": "<?php echo $editorCount["loggedin"]; ?> (IP: <?php echo $editorCount["anonymous"]; ?>)",
				"<?php echo $this->translate( array( "groupStats", "references" ) ); ?>": "<?php echo SingletonFactory::getInstance( 'Api_Model' )->getCurrentRevision(); ?>",
				"<?php echo $this->translate( array( "groupStats", "images" ) ); ?>": "<?php echo $this->getImageCount(); ?>",
<?php $stats = SingletonFactory::getInstance( "WebService_StatsGrok" )->getClassicStats( WebService_StatsGrok::BOTH, $this->getTitle(), $this->getLang() ); ?>
				"<?php echo $this->translate( array( "groupStats", "visitorsYesterday" ) ); ?>": "<?php echo $stats["yesterday"]; ?>",
				"<?php echo $this->translate( array( "groupStats", "visitorsLastMonth" ) ); ?>": "<?php echo  $stats["monthly"]; ?>"
			}
		},
		
		"factCoverage": {
			"title": "<?php echo $this->translate( array( "groupCoverage", "title" ) ); ?>",
			"items": {
				"<?php echo $this->translate( array( "groupCoverage", "lea" ) ); ?>": [ "<?php echo $this->translate( array( "groupCoverage", "showAnalysis" ) ); ?>", "http://toolserver.org/~<?php echo $uName;?>/toolkit/LEA/index.php?submit=1&title=<?php echo $this->getTitle(); ?>&lg=<?php echo SingletonFactory::getInstance( 'Request' )->getVar( 'lang' ); ?>&lang=<?php echo SingletonFactory::getInstance( 'Request' )->getVar( 'lang' ); ?>" ]
			}
		},
<?php $newsCount = $this->getNewsItems(); ?>
<?php $cdHit = SingletonFactory::getInstance( 'ChangeDetector_Model' )->checkDetected( $this->getId(), $this->getLang() ); ?>
<?php if ( $newsCount || $cdHit ): ?>
		"currentness": {
			"title": "<?php echo $this->translate( array( "groupCurrentness", "title" ) ); ?>",
			"items": {
	<?php if ( $newsCount ): ?>,
				"<?php echo $this->translate( array( "groupCurrentness", "titleNewsFinder" ) ); ?>": [ "<?php echo $this->getNewsItems(); ?>", "http://toolserver.org/~<?php echo $uName;?>/stools/asqm/query/news/title/<?php echo $this->getTitle(); ?>"]
	<?php endif; ?>,
	<?php if ( $cdHit ): ?>,
		<?php SingletonFactory::getInstance( "Asqm_Model" )->logRequest( $this->getTitle(), $this->getLang(), ( isset( $_SESSION['asqmId'] ) && !empty( $_SESSION['asqmId'] ) ) ? $_SESSION['asqmId'] : "none", "cd-show", "" ); ?>
	"<?php echo $this->translate( array( "groupCurrentness", "titleChangeDetector" ) ); ?>": [ "<?php echo $this->translate( array( "groupCurrentness", "cdHit" ) ); ?>", "http://toolserver.org/~<?php echo $uName;?>/toolkit/ChangeDetector/index.php?Cuthalf=on&Sorting=No_change&filterMU=on&filterNB=on&filterOM=on&day=<?php echo date( "Ymd", time() - ( 86400 * 2 ) ); ?>&Langgroup=EU&Reflang=<?php echo $this->getLang() ;?>&submit=%C3%9Cbermitteln#result_table" ]
	<?php endif; ?>
			}
		},
<?php endif; # $newsCount OR $cdHit ?>
<?php $giniScore = SingletonFactory::getInstance( 'Asqm_Model' )->getGiniScore( $this->getId(), $this->getLang() ); ?>
<?php if ( $giniScore ): ?>
	<?php SingletonFactory::getInstance( "Asqm_Model" )->logRequest( $this->getTitle(), $this->getLang(), ( isset( $_SESSION['asqmId'] ) && !empty( $_SESSION['asqmId'] ) ) ? $_SESSION['asqmId'] : "none", "wikigini-show", $giniScore ); ?>
		"editorInteraction": {
			"title": "<?php echo $this->translate( array( "groupEditorInteraction", "title" ) ); ?>",
			"items": {
				"<?php echo $this->translate( array( "groupEditorInteraction", "giniScore" ) ); ?>": [ "<?php echo $giniScore; ?>", "http://toolserver.org/~<?php echo $uName;?>/toolkit/WIKIGINI/?language_code=<?php echo $this->getLang(); ?>&page_id=<?php echo $this->getId(); ?>" ]
			}
		},
<?php endif; ?>
		
<?php if ( SingletonFactory::getInstance( 'Request' )->getVar( 'lang' ) == 'de' ): ?>
		"other": {
			"title": "<?php echo $this->translate( array( "groupOther", "title" ) ); ?>",
			"items": {
				"<?php echo $this->translate( array( "groupOther", "wikibuch" ) ); ?>": [ "<?php echo $this->translate( array( "groupOther", "lookupAssessment" ) ); ?>", "http://wikibu.ch/search.php?search=<?php echo $this->getTitle(); ?>" ]
			}
		},
<?php endif; ?>
<?php #if ( $this->_lang /*SingletonFactory::getInstance( 'Request' )->getVar( 'lang' )*/ == 'en' ): ?>
<?php $percent = SingletonFactory::getInstance( 'Api_Model' )->getArticleFeedback5(); ?>
<?php if ( !empty( $percent ) ): ?>
	<?php SingletonFactory::getInstance( "Asqm_Model" )->logRequest( $this->getTitle(), $this->getLang(), ( isset( $_SESSION['asqmId'] ) && !empty( $_SESSION['asqmId'] ) ) ? $_SESSION['asqmId'] : "none", "aft5-show", $percent ); ?>
		"aft-v5": {
			"title": "<?php echo $this->translate( array( "groupAftV5", "title" ) ); ?>",
			"items": {
				"<?php echo $this->translate( array( "groupAftV5", "negRating" ) ); ?>": [ "<?php echo $percent; ?> %", "http://en.wikipedia.org/wiki/Special:ArticleFeedbackv5/<?php echo $this->getTitle(); ?>" ]
			}
		},
<?php else: ?>
<?php $ratings = SingletonFactory::getInstance( 'Api_Model' )->getArticleFeedback(); ?>
<?php if ( !empty( $ratings ) ): ?>
	<?php SingletonFactory::getInstance( "Asqm_Model" )->logRequest( $this->getTitle(), $this->getLang(), ( isset( $_SESSION['asqmId'] ) && !empty( $_SESSION['asqmId'] ) ) ? $_SESSION['asqmId'] : "none", "aft4-show", base64_encode( serialize( $ratings ) ) ); ?>
		"aft-v4": {
			"title": "<?php echo $this->translate( array( "groupAftV4", "title" ) ); ?>",
			"items": {
				"<?php echo $this->translate( array( "groupAftV4", "trustworthy" ) ); ?>": "<?php echo number_format( $ratings[0], 1 ); ?>",
				"<?php echo $this->translate( array( "groupAftV4", "objective" ) ); ?>": "<?php echo number_format( $ratings[1], 1 ); ?>",
				"<?php echo $this->translate( array( "groupAftV4", "complete" ) ); ?>": "<?php echo number_format( $ratings[2], 1 ); ?>",
				"<?php echo $this->translate( array( "groupAftV4", "wellWritten" ) ); ?>": "<?php echo number_format( $ratings[3], 1 ); ?>"
			}
		}
<?php endif; # v4 is not available ?>
<?php endif; # get v4, because v5 is not available ?>
<?php #endif; # only english lang version ?>
	}
})

