<div class="tlg-header box-shadow" style="padding-top: 20px; text-align: center;">
	<a href="<?php echo BASE_PATH; ?>feedback/form"><img src="<?php echo BASE_PATH; ?>res/img/feedback.png" style="vertical-align: middle; padding: 10px;" /></a>
	<span>
		<a href="<?php echo BASE_PATH; ?>feedback/form"><?php echo $this->translate( "helpUs", "common" ); ?></a><?php echo $this->translate( "improveStools", "common" ); ?>
	</span><br />
	<img src="<?php echo BASE_PATH; ?>res/img/fp7.png" style="vertical-align: middle; padding: 10px;" />
	<span>
		<?php echo $this->translate( "euFunded", "common" ); ?>
	</span><br /><br />
	<?php echo $this->translate( "disclaimer", "common" ); ?>
	<em><?php echo $this->translate( "developers", "common" ); ?></em>
</div>