<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>Supporting Tools für Wikipedia</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		
		<link rel="stylesheet" type="text/css" href="<?php echo BASE_PATH; ?>res/css/alg_html.css" />
		<script type="text/javascript" src="<?php echo BASE_PATH; ?>res/js/jquery-1.8.0.min.js"></script>
	</head>

	<body>
		<div class="alg-container box-shadow">
<?php include( APP_PATH . "../templates/pageHeading.phtml" ); ?>

			<div style="padding-top: 10px;">
				<h2><?php echo $this->translate( "newsfeedHeading" ); ?></h2>
				<p><?php echo $this->translate( "newsfeedDesc" ); ?></p>
				<div id="resultContainer" class="box-shadow">
<?php $title = SingletonFactory::getInstance( 'Request' )->getVar( 'title' ); ?>
<?php $lang = SingletonFactory::getInstance( 'Request' )->getVar( 'lang' ); ?>
<?php $page = SingletonFactory::getInstance( 'Request' )->getVar( 'page' ); ?>
<?php $nfModel = SingletonFactory::getInstance( 'Newsfeed_Model' ); ?>
<?php $nfModel->setArticleTitle( $title, $lang ); ?>
<?php $items = SingletonFactory::getInstance( 'Newsfeed_Model' )->getNewsArticles( $page ); ?>
<?php $itemCount = SingletonFactory::getInstance( 'Newsfeed_Model' )->getItemCount(); ?>
<?php if ( is_array( $items ) ): ?>
					<table>
						<tr>
							<th><?php echo $this->translate( "newsfeedTableDate" ); ?></th>
							<th><?php echo $this->translate( "newsfeedTableTitle" ); ?></th>
							<th><?php echo $this->translate( "newsfeedTableUrl" ); ?></th>
						</tr>
	<?php foreach ($items as $item): ?>
						<tr>
							<td><?php echo date( $this->translate( "dateFormat" ), strtotime( $item->DateTime ) ); ?></td>
							<td><?php echo $item->Title; ?></td>
							<td><a href="<?php echo $item->URI; ?>" target="_blank"><?php echo $this->shortenUrl( $item->URI ); ?></a></td>
						</tr>
	<?php endforeach; ?>
					</table>
					<div>
	<?php if ( $page > 0 ): ?>
						<p style="float: left;"><a href="<?php echo BASE_PATH; ?>articleMonitor/query/news/title/Berlin/lang/de/page/<?php echo ($page - 1); ?>">Zurück</a></p>
	<?php else: ?>
						<p style="float: left;"><span style="color: silver;">Zurück</span></p>
	<?php endif; ?>
	<?php if ( ceil( $itemCount / 10 ) > $page ): ?>
						<p style="float: right;"><a href="<?php echo BASE_PATH; ?>articleMonitor/query/news/title/<?php echo $title; ?>/lang/<?php echo $lang; ?>/page/<?php echo ($page + 1); ?>">Vor</a></p>
	<?php else: ?>
						<p style="float: right;"><span style="color: silver;">Vor</span></p>
	<?php endif; ?>
					</div>
<?php else: ?>
					<span style="margin-left: 10px;">Keine Artikel gefunden.</span>
<?php endif; ?>
				</div>
			</div>
<?php require( 'disclaimer.phtml' ); ?>
		</div>
	</body>
</html>
