<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>Supporting Tools für Wikipedia</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		
		<link rel="stylesheet" type="text/css" href="<?php echo BASE_PATH; ?>res/css/tlg_html.css" />
		<script type="text/javascript" src="<?php echo BASE_PATH; ?>res/js/jquery-1.8.0.min.js"></script>
	</head>

	<body>
		<div class="tlg-container box-shadow">
<?php include( APP_PATH . "../templates/pageHeading.phtml" ); ?>

			<div style="padding-top: 10px;">
				<h2><?php echo $this->translate( "newsfeedHeading" ); ?></h2>
				<p><?php echo $this->translate( "newsfeedDesc" ); ?></p>
				<div id="resultContainer" class="box-shadow">
<?php $title = SingletonFactory::getInstance( 'Request' )->getVar( 'title' ); ?>
<?php $items = SingletonFactory::getInstance( 'Newsfeed_Model' )->getNewsArticles( $title ); ?>
<?php if ( is_array( $items ) ): ?>
					<table>
						<tr>
							<th><?php echo $this->translate( "newsfeedTableDate" ); ?></th>
							<th><?php echo $this->translate( "newsfeedTableTitle" ); ?></th>
							<th><?php echo $this->translate( "newsfeedTableUrl" ); ?></th>
						</tr>
	<?php foreach ($items as $item): ?>
						<tr>
							<td><?php echo date( $this->translate( "dateFormat" ), strtotime( $item->DateTime ) ); ?></td>
							<td><?php echo $item->Title; ?></td>
							<td><a href="<?php echo $item->URI; ?>" target="_blank"><?php echo $this->shortenUrl( $item->URI ); ?></a></td>
						</tr>
	<?php endforeach; ?>
					</table>
<?php else: ?>
					<span style="margin-left: 10px;">Keine Artikel gefunden.</span>
<?php endif; ?>
				</div>
			</div>
<?php require( 'disclaimer.phtml' ); ?>
		</div>
	</body>
</html>
