			<div class="tlg-header box-shadow">
				<p>
					<img src="<?php echo BASE_PATH; ?>res/img/logo-wmde.png" height="60" class="logoLeft" />
					<img src="<?php echo BASE_PATH; ?>res/img/logo-render.png" height="60" class="logoRight" />
				</p>
				<h1 style="text-align: center;"><?php echo $this->translate( "pageHeading", "common" ); ?></h1>
			</div>
			<div class="clear"></div>
			<p style="width: 100%; text-align: right;"><?php echo $this->translate("langSwitch", "common"); ?></p>
