<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<title>TLG - Task List Generator</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		
		<link rel="stylesheet" type="text/css" href="<?php echo BASE_PATH; ?>res/css/tlg_html.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo BASE_PATH; ?>res/css/smoothness/jquery-ui.min.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo BASE_PATH; ?>res/css/smoothness/jquery.ui.theme.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo BASE_PATH; ?>res/css/jquery.tagedit.css" />
		<script type="text/javascript" src="<?php echo BASE_PATH; ?>res/js/jquery-1.8.0.min.js"></script>
		<script type="text/javascript" src="<?php echo BASE_PATH; ?>res/js/jquery-ui-1.10.2.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo BASE_PATH; ?>res/js/jquery.tagedit.js"></script>
		<script type="text/javascript" src="<?php echo BASE_PATH; ?>res/js/jquery.autoGrowInput.js"></script>
		<script type="text/javascript" src="<?php echo BASE_PATH; ?>res/js/tlg_html.js"></script>
		<script type="text/javascript">
			var basePath = '<?php echo BASE_PATH; ?>';
			var reqSuccess = '<?php echo $this->translate("reqSuccess"); ?>';
			var reqSuccessMsg = '<?php echo $this->translate("reqSuccessMsg"); ?>';
			var tableHeadFlaw = '<?php echo $this->translate("tableHeadFlaw"); ?>';
			var tableHeadPage = '<?php echo $this->translate("tableHeadPage"); ?>';
			var errNoFilter = '<?php echo $this->translate("errNoFilter"); ?>';
			var errNoAddress = '<?php echo $this->translate("errNoAddress"); ?>';
			var statusMarkedHidden = '<?php echo $this->translate("markedAsHidden"); ?>';
			var statusUnmarkedHidden = '<?php echo $this->translate("unmarkedAsHidden"); ?>';
			var descHide = '<?php echo $this->translate("descHide"); ?>';
			var descUnhide = '<?php echo $this->translate("descUnhide"); ?>';
			var descLinkToRequest = '<?php echo $this->translate("linkToRequest"); ?>';
			var msgResultCount = '<?php echo $this->translate("resultCount"); ?>';
			var tlgServiceUrl = '<?php echo TLG_SERVICE_URL; ?>';
		</script>
	</head>

	<body>
		<div class="tlg-container box-shadow">
<?php include( APP_PATH . "../templates/pageHeading.phtml" ); ?>
			<form id="tlg-form" action="">
				<div>
					<h2><?php echo $this->translate( "topHeading" ); ?></h2>
					<div style="float: left; width: 50%;">
						<div><?php echo $this->translate("tlgDescription"); ?></div><br /><br />
						<h3 style="margin-top: 0;"><?php echo $this->translate( "descHeading" ); ?></h3>
						<label class="selectLabel" for="language">
							<?php echo $this->translate( "descLanguage" ); ?>
						</label>
						<select name="lang" id="language">
<?php $graphs = SingletonFactory::getInstance( 'Tlg_Model' )->getGraphList(); ?>
<?php if( is_array( $graphs ) ): ?>
<?php foreach( $graphs as $graph ): ?>
							<option value="<?php echo $graph; ?>" <?php echo ( isset( $_GET['lang'] ) && $_GET['lang'] == $graph ) ? "selected" : ""; ?>><?php echo $graph; ?></option>
<?php endforeach; ?>
<?php endif; ?>
						</select>
						<img class="fldHelp" id="helpLanguage" src="<?php echo BASE_PATH; ?>res/img/emblem-notice.png" />
						<div class="clear"></div>

						<label class="textLabel" for="categories">
							<?php echo $this->translate( "descCategories" ); ?>
						</label>
						<div style="float: left; margin-right: 5px;">
<?php $query = SingletonFactory::getInstance( "Request" )->getVar( "query" ); ?>
							<input type="text" id="categories" class="taggable" name="query[]" value="<?php echo $query; ?>" />
						</div>
						<img class="fldHelp" id="helpCategories" style="padding-top: 5px;" src="<?php echo BASE_PATH; ?>res/img/emblem-notice.png" />
						<div class="clear"></div>
						<div style="font-size: 0.8em; margin: 0 0 14px 130px;"><?php echo $this->translate("descCategoriesMore"); ?></div>

						<label class="textLabel" for="depth">
							<?php echo $this->translate( "descDepth" ); ?>
						</label>
						<input type="text" id="depth" name="querydepth" value="<?php echo isset( $_GET['querydepth'] ) ? htmlentities( $_GET['querydepth'] ) : "2"; ?>" />
						<img class="fldHelp" id="helpDepth" src="<?php echo BASE_PATH; ?>res/img/emblem-notice.png" />
						<div class="clear"></div>

						<!--input style="margin-left: 110px;" type="checkbox" id="include_hidden" name="include_hidden" value="true" <?php echo isset( $_GET['include_hidden'] ) ? "checked" : ""; ?> />
						<label style="width: 100px;" for="include_hidden">
							<?php echo $this->translate( "alsoShowHidden" ); ?>
						</label>
						<div class="clear"></div-->

						<label class="selectLabel" for="outputFormat">
							<?php echo $this->translate( "descFormat" ); ?>
						</label>
						<select id="outputFormat" name="format">
							<option value="html" <?php echo SingletonFactory::getInstance( 'Request' )->getVar( 'format' ) == "html" ? "checked" : ""; ?>>HTML</option>
							<option value="wikitext" <?php echo SingletonFactory::getInstance( 'Request' )->getVar( 'format' ) == "wikitext" ? "checked" : ""; ?>>WikiText</option>
						</select>
						<!--div class="clear"></div-->

						<input type="checkbox" id="bymail" name="bymail" <?php echo SingletonFactory::getInstance( 'Request' )->getVar( 'bymail' ) == "on" ? "checked" : ""; ?> onclick="javascript:toggleAddressField();" value="on" />
						<label style="width: 100px;" for="bymail">
							<?php echo $this->translate( "labelAddressCb" ); ?>
						</label>
						<img class="fldHelp" id="helpOutput" src="<?php echo BASE_PATH; ?>res/img/emblem-notice.png" />
						<div class="clear"></div>

						<div id="divAddress" style="visibility: <?php echo isset( $_GET['bymail'] ) ? "visible" : "hidden"; ?>;">
							<label class="fieldLabel" for="address">
								<?php echo $this->translate( "labelAddress" ); ?>
							</label>
							<input type="text" id="address" name="mailto" value="<?php echo isset( $_GET['mailto'] ) ? htmlentities( $_GET['mailto'] ) : ""; ?>" />
						</div>
						<div class="clear"></div>

						<button id="btnSearch"><?php echo $this->translate( "labelSearch" ); ?></button>
						<div class="clear"></div>
					</div>
					<div style="margin-left: 60%">
						<h3><?php echo $this->translate( "formHeading" ); ?></h3>
<?php foreach ($this->getFlaws() as $group => $flaws): ?>
						<div class="cbGroupContainer">
	<?php if ( !empty( $group ) ): ?>
							<h4><input type="checkbox" class="cbGroup" id="<?php echo $group; ?>" /><?php echo $group; ?></h4>
	<?php else: ?>
							<h4><?php echo $this->translate( "filterGeneral" ); ?></h4>
	<?php endif; ?>
	<?php foreach ($flaws as $name => $info): ?>
		<?php $name = str_replace( ":", "-", $name); ?>
							<input type="checkbox" class="cbFilter <?php echo ( $group !== '' ) ? $group : 'general'; ?>" id="<?php echo $name; ?>" name="flaw" value="<?php echo $name; ?>" style="margin-left: 18px;" <?php echo ( isset( $_GET['flaws'] ) && strstr( $_GET['flaws'], $name ) ) ? "checked" : ""; ?> />
							<label class="cbLabel" title="<?php echo $info["description"]; ?>" for="<?php echo $name; ?>"><?php echo $info["label"]; ?></label><br />
	<?php endforeach; ?>
						</div>
<?php endforeach; ?>
						<div class="clear"></div>
					</div>
				</div>
				<input type="hidden" name="i18n" value="<?php echo $this->getLang(); ?>" />
			</form>
			<div id="resultContainer" class="box-shadow box-hidden">
				<div id="resultInfo"></div>
				<div id="resultTable"></div>
			</div>
<?php require( 'disclaimer.phtml' ); ?>
		</div>
		
		<div id="statusDialog" title="<?php echo $this->translate( "statusTitle" ); ?>">
			<p>
				<span id="status"> </span>
				<div id="tlgProgress"></div>
			</p>
		</div>

		<div id="actionDialog" title="<?php echo $this->translate( "statusTitle" ); ?>">
			<p>
				<span id="action"> </span>
			</p>
		</div>

		<div id="dlg-helpLanguage" title="<?php echo $this->translate( "descLanguage" ); ?>">
			<p>
				<?php echo $this->translate( "descLanguageDesc" ); ?>
			</p>
		</div>

		<div id="dlg-helpCategories" title="<?php echo $this->translate( "descCategories" ); ?>">
			<p>
				<?php echo $this->translate( "descCategoriesDesc" ); ?>
			</p>
		</div>

		<div id="dlg-helpDepth" title="<?php echo $this->translate( "descDepth" ); ?>">
			<p>
				<?php echo $this->translate( "descDepthDesc" ); ?>
			</p>
		</div>

		<div id="dlg-helpOutput" title="<?php echo $this->translate( "descOutput" ); ?>">
			<p>
				<?php echo $this->translate( "descOutputDesc" ); ?>
			</p>
		</div>

		<div id="dlgError" title="<?php echo $this->translate( "dlgErrorTitle" ); ?>">
			<strong><?php echo $this->translate( "dlgErrorHeading" ); ?></strong>
			<p id="errMsg"></p>
			<!--p><?php echo $this->translate( "dlgErrorReport" ); ?></p-->
		</div>
<?php if( isset( $_GET['submit'] ) && $_GET['submit'] == 'true' ): ?>
		<script>
			$( document ).ready( function() {
				$( "#btnSearch" ).click();
			});
		</script>
<?php endif; ?>
	</body>
</html>
