<?php
$Headline = "WIKIGINI";
$Description = "WIKIGINI visualizes the inequality of authorship in a Wikipedia article: it accurately determines the authors of all the words in every revision of an article and calculates a so-called “Gini-Index” as a measure of inequality. It can thus show if the “ownership” of words in an article shifted from being quite equal (e.g. every editor wrote about the same amount of words) to being unequal (e.g. 2% of editors wrote 90% of the words).";

$MoreInfo = "More information";

?>
