<?php
$Headline = "WIKIGINI";
$Description = "The amounts of text written by the authors of a Wikipedia 
	article can be visualized by WikiGini. It also illustrates these edits 
	over the course of time.<br /> 
	<br />
	For every revision of an article WikiGini determines the amount of 
	words each author has written. These data are used to calculate the 
	Gini Index as a measure of statistical dispersion. The result is 
	displayed in the form of a graph that allows to determine whether the 
	authors of a certain article are evenly distributed. It is also 
	possible to see how the distribution of text by a number of authors 
	has changed over time, e.g. when it changed from a relatively even 
	distribution (every author wrote almost the same amount of content) 
	to a very uneven distribution (a small number of authors wrote the 
	majority of the text).";
$Headline2 = "Example";
$Description2 = "The example shows the graph for the Wikipedia article 
	about Barack Obama. The Gini Index may range between zero and one. 
	The lower this index is, the more even is the distribution of text 
	per author. The higher this index gets, the more uneven the 
	distribution gets. A score of zero means that each author wrote the 
	same amount of words. A score of one indicates that only one author 
	wrote the whole article.<br />
	By means of the buttons below the graph it is possible to either 
	display the date or individual revisions at certain points in time. 
	It is also possible to change pages back and forth. Moving the mouse 
	over the graph, a popup window appears and shows details for a 
	specific revision/a specific date. You can zoom in on the graph by 
	selecting an area with the mouse.";
s$MoreInfo = "More information";
$txtGraphHeader1 = "WIKIGINI - Article ";
$txtGraphHeader2 = " in language ";
$txtSwitchRevision = "Switch to revisions mode";
$txtSwitchTime = "Switch to time mode";
?>
