<?php
$Headline = "WIKIGINI";
$Description = "WikiGini visualizes the distribution of authorship in a 
	Wikipedia article in the course of time.<br /><br />
	For every revision of an article it determines the amount of words 
	for each author and calculates the Gini Index as a measure of 
	statistical dispersion. The result is displayed using a diagram. You 
	can see if the authorship of an article is evenly distributed and 
	how it changes in the course of time.";
$Headline2 = "Example";
$Description2 = "The example shows the diagram to the Wikipedia article 
	about Barack Obama. The Gini Index may range between zero and one. A 
	score of zero means perfect equality (each author owns the same 
	amount of words). A score of one indicates maximal inequity (one 
	single author wrote the whole article).<br /><br />
	Using the buttons below the chart you can switch between the display 
	of revision and date on the timeline and you can move back and forth. 
	Moving the mouse over the diagram a popup window appears and shows 
	details for the specific revision. You can zoom in an area of the 
	diagram by selecting it with the mouse.";

$MoreInfo = "More information";
$txtGraphHeader1 = "WIKIGINI - Article ";
$txtGraphHeader2 = " in language ";
$txtSwitchRevision = "Switch to revisions mode";
$txtSwitchTime = "Switch to time mode";
?>
