<?php

$Headline = "Über uns";
$Introduction = "Wikimedia Deutschland ist Anwendungspartner im Forschungsprojekts RENDER (Reflecting Knowledge Diversity). Wir untersuchen gemeinsam mit unserern Projektpartnern Diversität in Wikipedia. Diversität ist wichtig, da sie Ergebnis einer vollständigen Faktenlage und einer angemessenen Darstellung aller Standpunkte ist. Diversität ermöglicht eine enzyklopädische, neutrale Darstellung.";


$Text1 = "<p>Bei unseren Untersuchungen orientieren wir uns an den Maßstäben für Qualität, die in Wikipedia gelten. 
Die Kriterien, die wir berücksichtigen, sind: 
</p>
<ul><li> thematische Abdeckung 
</li><li> Aktualität
</li><li> Objektivität
</li></ul>
<p>Darüber hinaus untersuchen wir auch Besonderheiten in der Interaktion der Nutzer.
Weitere Informationen zum Projekt finden sich unter <a href=\"http://de.wikipedia.org/wiki/Wikipedia:RENDER\">Wikipedia:RENDER</a> bzw. <a href=\"http://render-project.eu\">http://render-project.eu</a>.
</p><p>
Die hier bereitgestellten Werkzeuge geben einen Einblick in die verschiedenen Diversitätsanalysen, die im Rahmen des RENDER-Projekts durchgeführt werden. 
</p>";

$Text2 = "<p>Im weiteren Verlauf des Projekts intergrieren wir die Ergebnisse in zwei verschiedene Anwendungen. Diese führen Nutzer gezielt zu Stellen in der Wikipedia, die verbesserungswürdig sind.
</p><p>Derzeit sind zwei dieser weiterführenden Werkzeuge geplant:
</p>
<ul><li> ein Qualitätsübersichtswerkzeug: dieses Werkzeug zeigt für jeden WP-Artikel die Ergebnisse an. Dieses Tool wird auch die Möglichkeit bieten verschiedene weitere Analysemetriken mit einzubeziehen und liefert einen schnellen Überblick über die Qualität und den Zustand eines Artikels,
</li><li> ein Arbeitslistengenerator: Damit kann ein Wikipedia-Autor für einen bestimmten Themenbereich bzw. seine bevorzugte Kategorie Listen verbesserungswürdiger Artikel generieren.
</li></ul>
<p>Die Werkzeuge können keine abschließende Antwort auf die Frage geben, ob ein Artikel unvollständig ist oder durch eine bestimmte Weltanschauung geprägt ist. Dazu bedarf es weiterhin menschlicher Urteilskraft. Die Werkzeuge können lediglich Hinweise auf problematische Artikel liefern. Diese Artikel können dann von Menschen überprüft und korrigiert werden. Dank der automatisierten Überprüfung von Artikeltexten lässt sich Zeit sparen, die dann für die Ergänzung oder Verbesserung verwendet werden kann. Außerdem wird so technisch Mangel an Diversität sichtbar gemacht, der manuell nicht in vertretbarer Zeit aufzudecken wäre.
</p>";

$Text3 = "<p>Das Toolkit und auch die einzelnen Werkzeuge befinden sich in einem kontinuierlichen Entwicklungsprozess. Wir freuen uns über Anregungen, Rückmeldungen und Ideen auf <a href=\"http://de.wikipedia.org/wiki/Wikipedia_Diskussion:RENDER\">Wikipedia_Diskussion:RENDER</a> oder per E-Mail an <a href=\"mailto:render@wikimedia.de\">render@wikimedia.de</a>.
</p>";



?>
