<?php

$Headline = "Über uns";
$Introduction = "Wikimedia Deutschland e. V. ist Anwendungspartner im RENDER-Projekt. Der Textkorpus von Wikipedia bietet sich als Forschungsgegenstand an, da er mehrsprachig, strukturiert und verfügbar ist. Der Wikipedia-Community wollen wir mit diesem Toolkit Software, die im Rahmen des Projektes entsteht, gebündelt zur Verfügung stellen. Damit wird Analyse und Verbesserung von Wikipedia unter Berücksichtigung von <i>Diversity</i> ermöglicht.";

?>
