<?php

$Headline = "Kontakt";
$Introduction = "Das RENDER-Team von Wikimedia Deutschland erreichen Sie am besten per E-Mail: <a href=\"mailto:render@wikimedia.de\">render@wikimedia.de</a>";

$Acknoledgments["Headline"] = "Danksagung";
$Acknoledgments["Text"] = "RENDER wird durch das <a href=\"http://cordis.europa.eu/fp7/home_en.html\">Siebte Rahmenprogramm</a> der Europäischen Kommission finanziert." ;

?>
