<?php

$Headline = "Kontakt";
$Introduction = "Das RENDER-Team von Wikimedia Deutschland erreichen Sie am besten per E-Mail: <a href=\"mailto:render@wikimedia.de\">render@wikimedia.de</a>";

$Acknoledgments["Headline"] = "Danksagung";
$Acknoledgments["Text"] = "RENDER wird von der <a href=\"http://europa.eu\">Europäischen Union</a> finanziert und ist Teil des <a href=\"http://cordis.europa.eu/fp7/home_en.html\"> Seventh Framework Programme</a>." ;


?>
