<?php
$Headline = "Downloads";

$Introduction = "";

$dlHeadName = "Dateiname";
$dlHeadSize = "Größe";
$dlHeadDesc = "Beschreibung";

$files = array(
	array(
		"name" => "20120323-en-updates.json.gz",
		"link" => "20120323-en-updates.json.gz",
		"size" => "5,5 GB",
		"desc" => "<p>Wikipedia Historical Attributes Data (WHAD) von Google 
			Research Zurich</p>
			<p>Diese Datei enthält ist eine Sammlung 
			der Veränderungen an den Infobox-Attributen. Enthalten sind 
			über 500 Millionen Änderungen, die seit 2003 vorgenommen 
			wurden. In der <a href=\"whad-sample.json.txt\" target=\"_blank\">
			Beispieldatei</a> befindet sich ein Überblick über die 
			verwendete Datenstruktur.</p>
			<p>Die Datensätze enthalten Informationen der unter Creative 
			Commons-Lizenz CC-BY-SA stehenden Wikipedia. Google stellt
			keinerlei urheberrechtliche oder andere rechtliche Ansprüche
			an den Inhalt und schlägt die Nutzung unter der Lizenz Creative 
			Commons Zero (CC0) vor. Wir empfehlen eine Kennzeichnung nach 
			folgendem Schema:<br />
			Guillermo Garrido, Enrique Alfonseca, Jean-Yves Delort and Anselmo 
			Peñas: Extracting Wikipedia Historical Attributes Data, in 
			Proceedings of Wikipedia Academy, Berlin, 2012<br />
			<a href=\"http://alfonseca.org/eng/research/whad.html\" target=\"_blank\">http://alfonseca.org/eng/research/whad.html</a></p>",
	),
	array(
		"name" => "neutrality-extractions-enwiki.7z",
		"link" => "neutrality-extractions-enwiki.7z",
		"size" => "244 MB",
		"desc" => "<p>Dieses Datenset enthält eine historische Zusammenfassung der <strong>englischsprachigen</strong> Artikel, in denen die Vorlage zur mangelnden Neutralität gesetzt und nach entsprechender inhaltlicher Änderung mindestens sieben Tage nicht wieder eingfügt wurde.</p><p>Extrahiert wurden jeweils zwei Versionen der relevanten Artikel: Die Version, in der mangelnde Neutralität aufgefallen ist und die, in der dieser Mangel offenbar behoben wurde.</p>",
	),
	array(
		"name" => "neutrality-extractions-dewiki.7z",
		"link" => "neutrality-extractions-dewiki.7z",
		"size" => "30 MB",
		"desc" => "<p>Dieses Datenset enthält eine historische Zusammenfassung der <strong>deutschsprachigen</strong> Artikel, in denen die Vorlage zur mangelnden Neutralität gesetzt und nach entsprechender inhaltlicher Änderung mindestens sieben Tage nicht wieder eingfügt wurde.</p> <p>Extrahiert wurden jeweils zwei Versionen der relevanten Artikel: Die Version, in der mangelnde Neutralität aufgefallen ist und die, in der dieser Mangel offenbar behoben wurde.</p>",
	),
);
?>
