<?php
$Headline = "Downloads";

$Introduction = "";

$dlHeadName = "Dateiname";
$dlHeadSize = "Größe";
$dlHeadDesc = "Beschreibung";

$files = array(
	array(
		"name" => "20120323-en-updates.json.gz",
		"link" => "http://ortelius.toolserver.org:83/~render/toolkit/downloads/20120323-en-updates.json.gz",
		"size" => "5,5 GB",
		"desc" => "Wikipedia Historical Attributes Data (WHAD) von Google 
			Research Zurich<br />Diese Datei enthält ist eine Sammlung 
			der Veränderungen an den Infobox-Attributen. Enthalten sind 
			über 500 Millionen Änderungen, die seit 2003 vorgenommen 
			wurden. In der <a href=\"/".$tsAccount."/toolkit/downloads/whad-sample.json.txt\" target=\"_blank\">
			Beispieldatei</a> befindet sich ein Überblick über die 
			verwendete Datenstruktur.<br />
			Die Datensätze enthalten Informationen der unter Creative 
			Commons-Lizenz CC-BY-SA stehenden Wikipedia. Google stellt
			keinerlei urheberrechtliche oder andere rechtliche Ansprüche
			an den Inhalt und schlägt die Nutzung unter der Lizenz Creative 
			Commons Zero (CC0) vor. Wir empfehlen eine Kennzeichnung nach 
			folgendem Schema: Titel, URL.",
	),
);
?>
