<?php

$Headline = "RENDER-Toolkit";
$Introduction = "Hallo und willkommen auf den Seiten des RENDER-Toolkits!";

$Text1 = "Hier gibt es die Gelegenheit, Tools, die im Rahmen des <a href=\"http://render-project.eu/\">RENDER-Projektes</a> entwickelt und getestet werden, auszuprobieren. Die Werkzeuge dienen dazu, Text aus Wikipedia auf Diversität hin zu untersuchen. Diversität ist wichtig, da sie Ergebnis einer vollständigen Faktenlage und einer angemessenen Darstellung aller Standpunkte ist. Diversität ermöglicht eine enzyklopädische, neutrale Darstellung.";


 
$Text2 = "Die Werkzeuge können keine abschließende Antwort auf die Frage geben, ob ein Artikel unvollständig ist oder durch eine bestimmte Weltanschauung geprägt ist. Dazu bedarf es weiterhin menschlicher Urteilskraft. Die Werkzeuge können lediglich Hinweise auf problematische Artikel liefern. Diese Artikel können dann von Menschen überprüft und korrigiert werden. Dank der automatisierten Überprüfung von Artikeltexten lässt sich Zeit sparen, die dann für die Ergänzung oder Verbesserung verwendet werden kann. Außerdem wird so technisch Mangel an Diversität sichtbar gemacht, der manuell nicht in vertretbarer Zeit aufzudecken wäre.";

$Text3 = "Die Werkzeuge befinden sich zum Teil noch in Entwicklung. Am besten erreichen Sie uns per E-Mail an <a href=\"mailto:render@wikimedia.de\">render@wikimedia.de</a>. Wir freuen uns über jede Anregung oder Rückmeldung, die uns dabei hilft, die Tools zu erweitern oder zu verbessern.";

?>
