<?php

$Headline = "RENDER-Toolkit";
$Introduction = "Hallo und willkommen auf den Seiten des RENDER-Toolkits!";

$Text1 = "Hier gibt es die Gelegenheit verschiedene Tools auszuprobieren. Diese 
	entstehen im Rahmen des Forschungsprojekts RENDER (Reflecting Knowledge 
	Diversity), bei dem Wikimedia Deutschland Anwendungspartner ist. Diese 
	Werkzeuge geben einen Einblick in die verschiedenen  Diversitätsanalysen, 
	die im Rahmen des Projekts durchgeführt werden. Weitere Informationen zum 
	Projekt finden sich unter <a href=\"http://de.wikipedia.org/wiki/Wikipedia:RENDER\">
	Wikipedia:RENDER</a> bzw. <a href=\"http://render-project.eu/\">
	http://render-project.eu</a>.";

$Text2 = "Das Toolkit und auch die einzelnen Werkzeuge befinden sich in einem 
	kontinuierlichen Entwicklungsprozess. Wir freuen uns über Anregungen, 
	Rückmeldungen und Ideen auf <a href=\"http://de.wikipedia.org/wiki/Wikipedia_Diskussion:RENDER\">
	Wikipedia_Diskussion:RENDER</a> oder per Mail an <a href=\"mailto:render@wikimedia.de\">
	render@wikimedia.de</a>.";

$Text3 = "";