<?php
$Headline = "Impressum";
$Introduction = "Diese Website ist ein Angebot von Wikimedia Deutschland e. V.:";

$Adress = array(
	"Title" => "Wikimedia Deutschland - Gesellschaft zur Förderung Freien Wissens e. V.",
	"Postbox" => "Postfach 30 32 43",
	"Zip" => "10729 Berlin",
	"Phone" => "Telefon: +49(0)30-21915826-0",
	"Fax" => "Fax: +49(0)30-21915826-9",
	"Email" => "E-mail: <a href='mailto:info@wikimedia.de'>info@wikimedia.de</a>"
);

$Disclaimer = array(
	"Head" => "Haftungsausschluss",
	"Text1" => "Alle hier angeboteten Dienste werden von Wikimedia Deutschland im 
		Rahmen des RENDER-Projektes angeboten. Die Rechte liegen bei Wikimedia 
		Deutschland oder bei einem der Partner des RENDER-Projektes. Soweit nicht 
		anders angegeben sind die auf dieser Seite angezeigten Daten unter 
		<a href='http://creativecommons.org/licenses/by-sa/3.0/deed.de'>Creative 
		Commons Attribution-Share-Alike License 3.0</a> lizensiert.",
	"Text2" => "Die Inhalte dieses Webprojektes wurden sorgfältig geprüft und 
		nach bestem Wissen erstellt. Aber für die hier dargebotenen Informationen 
		wird kein Anspruch auf Vollständigkeit, Aktualität, Qualität und Richtigkeit 
		erhoben. Es kann keine Verantwortung für Schäden übernommen werden, die 
		durch das Vertrauen auf die Inhalte dieser Website oder deren Gebrauch 
		entstehen."
);