<?php

$Headline = "About us";
$Introduction = "Wikimedia Deutschland e. V. is Use-Case Partner in the RENDER Project. Wikipedia's Corpus can be seen as an ideal object of research: It is multilingual, structured and free. With this toolkit we would like to present Software from the RENDER project to the community. These tools are useful for analysis and improvement of Wikipedia as regards diversity.";

$Text1 = "";

$Text2 = "";

$Text3 = "";


?>
