<?php
$Headline = "Info";
$Introduction = "
	Wikimedia Deutschland is a use case partner in the research project 
	RENDER (Reflecting Knowledge Diversity). In cooperation with our 
	project partners we analyse and evaluate diversity in Wikipedia. 
	Diversity is important for Wikipedia because it is a result of 
	complete coverage of facts and a balanced representation of all 
	viewpoints. Diversity is necessary for an encyclopaedic and neutral 
	description.
";

$heading1 = "Metrics";
$Text1 = "
	<p>
		All our analysis focus on metrics for quality as they apply in 
		Wikipedia. We take the following criteria into account: 
	</p>
	<ul>
		<li>Completeness</li>
		<li>Timeliness</li>
		<li>Objectivity</li>
	</ul>
	<p>
		In addition, we investigate the characteristics of editor 
		interaction. For more information about the project, please visit 
		<a href=\"http://meta.wikimedia.org/wiki/RENDER\">
			RENDER on Meta-Wiki
		</a>
		or
		<a href=\"http://render-project.eu\">the project website</a>.
	</p>
	<p>
		The toolkit provides a first insight into our diversity analysis 
		in Wikipedia, as they will be implemented in the RENDER project. 
	</p>
";

$heading2 = "Planned Supporting Tools";
$Text2 = "
	<p>
		At a later stage of the project we are going to integrate the 
		results in different supporting applications. These tools will 
		lead users to locations in Wikipedia, which need to be improved.
		We are going to develop two supporting tools:
	</p>
	<ul>
		<li>
			Quality Overview Tool: This application displays the diversity 
			analysis results for every article. This tool will include 
			the possibility to check for different metrics and provide a 
			quick overview of the quality and the state of an article.
		</li>
		<li>
			Task List Generator: This application enables a Wikipedia 
			author to generate lists of articles related to a specific 
			topic or preferred category, which need to be improved.
		</li>
	</ul>
	<p>
		These supporting tools cannot and should not give an answer to 
		the question whether an article is incomplete or biased by 
		emphasis from a certain point of view. For that it still needs 
		human judgement. The tools can only provide advice for 
		problematic articles. These articles may be reviewed and 
		corrected by human beings.
		An automatic review of articles could save time. Saved time 
		could be used for completion and improvement of Wikipedia. 
		Furthermore it is possible to detect a lack of diversity with 
		technical aid, that cannot be done manually within reasonable 
		time.
	</p>
";

$heading3 = "";
$Text3 = "
	<p>
		The whole toolkit as well as the tools are in a continuous process 
		of development. We are looking forward to receiving suggestions, 
		feedback or ideas on 
		<a href=\"http://meta.wikimedia.org/wiki/Talk:RENDER\">
			discussion page concerning RENDER in Wikipedia
		</a>
		or by
		<a href=\"mailto:render@wikimedia.de\">email</a>.
	</p>
";
