<?php

$Headline = "About Us";
$Introduction = "Wikimedia Deutschland is use case partner in the RENDER project (Reflecting Knowledge Diversity). In cooperation with our project partners we analyze and evaluate diversity in Wikipedia.";

$Text1 = "Diversity is important as a result of a complete coverage of facts and an adequate representation of all viewpoints. Diversity is essential for an encyclopedic and neutral description. All our analyses focus upon metrics for quality as they apply in Wikipedia. We take the following criteria into account:
<ul> 
<li>Completeness</li>
<li>Timeliness</li>
<li>Objectivity</li>
</ul>";

$Text2 = "In addition we investigate the characteristics of editor interaction. For more information about project as a whole, please visit <a href=http://de.wikipedia.org/wiki/Wikipedia:RENDER>RENDER in Wikipedia</a> or <a href=http://render-project.eu>the project website</a>.
The tools on this page provide a first insight into different kinds of diversity analysis, as they will be implemented in the RENDER project. In the course of the project we integrate the results in different supporting applications. Using these tools the user will be enabled to discover articles in Wikipedia that need improvement.
At the moment we have plans for two of these supporting tools:
<ul>
<li>Quality Overview Tool: this application displays analysis for every article. This tool will include the possibility to check for different metrics and provide a quick overview of the quality and overall condition of an article.</li>
<li>Working List Generator: This application provides the user for a specific theme or preferred categorie lists of articles, which lacks refinement.</li>
</ul>";

$Text3 = "These supporting tools cannot and should not give an answer to the question whether an article is incomplete or biased by emphasis on a certain point of view. For that it still needs human judgement. The tools can only provide evidence for problematic articles. These articles have to reviewed and corrected by human beings.
An automatic review of articles could save time. Saved time could be used for completion and improvement of Wikipedia. Furthermore it is possible to detect a lack of diversity with technical aid, that cannot manually done within justifiable time. All of the tools as the toolkit itself are in a continuous process of development. We are looking forward to suggestions, feedback or ideas on <a href=http://de.wikipedia.org/wiki/Wikipedia_Diskussion:RENDER>RENDER in Wikipedia</a> or by e-mail to <a href=mailto:render@wikimedia.de>render@wikimedia.de</a>.";


?>
