<?php

$Headline = "Contact";
$Introduction = "Best way to reach the RENDER team at Wikimedia Deutschland is by e-mail: <a href=\"mailto:render@wikimedia.de\">render@wikimedia.de</a>";

$Acknoledgments["Headline"] = "Acknowledgements" ;
$Acknoledgments["Text"] = "RENDER is funded by the <a href=\"http://europa.eu\">European Union</a> and part of the <a href=\"http://cordis.europa.eu/fp7/home_en.html\"> Seventh Framework Programme</a>.";

?>
