<?php
$Headline = "Downloads";

$Introduction = "";

$dlHeadName = "File Name";
$dlHeadSize = "Size";
$dlHeadDesc = "Description";

$files = array(
	array(
		"name" => "20120323-en-updates.json.gz",
		"link" => "http://ortelius.toolserver.org:83/~render/toolkit/downloads/20120323-en-updates.json.gz",
		"size" => "5.5 GB",
		"desc" => "Wikipedia Historical Attributes Data (WHAD) provided 
			by Google Research Zurich<br />This file holds a 
			collection of value changes made to infobox attributes. It 
			holds more than 500 million attribute changes carried out
			since 2003. An overview of its structure is available in an 
			<a href=\"/".$tsAccount."/toolkit/downloads/whad-sample.json.txt\" target=\"_blank\">
			example file</a>.<br />
			The dataset contains information from the Creative Commons 
			cc-by-sa-licensed Wikipedia. Google does not assert any 
			copyright or other rights on this dataset and suggests that 
			the data can be used in line with the Creative Commons Zero 
			(CC0) license waiver. However, we suggest that one should 
			consider attributing the dataset as follows: Title, URL.<br />",
	),
);
