<?php
$Headline = "Downloads";

$Introduction = "";

$dlHeadName = "File Name";
$dlHeadSize = "Size";
$dlHeadDesc = "Description";

$files = array(
	array(
		"name" => "20120323-en-updates.json.gz",
		"link" => "20120323-en-updates.json.gz",
		"size" => "5.5 GB",
		"desc" => "<p>Wikipedia Historical Attributes Data (WHAD) provided 
			by Google Research Zurich</p><p>This file holds a 
			collection of value changes made to infobox attributes. It 
			holds more than 500 million attribute changes carried out
			since 2003. An overview of its structure is available in an 
			<a href=\"whad-sample.json.txt\" target=\"_blank\">
			example file</a>.</p> 
			<p>The dataset contains information from the Creative Commons 
			cc-by-sa-licensed Wikipedia. Google does not assert any 
			copyright or other rights on this dataset and suggests that 
			the data can be used in line with the Creative Commons Zero 
			(CC0) license waiver. However, we suggest that one should 
			consider attributing the dataset as follows:<br />
			Guillermo Garrido, Enrique Alfonseca, Jean-Yves Delort and Anselmo 
			Peñas: Extracting Wikipedia Historical Attributes Data, in 
			Proceedings of Wikipedia Academy, Berlin, 2012<br />
			<a href=\"http://alfonseca.org/eng/research/whad.html\" target=\"_blank\">
				http://alfonseca.org/eng/research/whad.html
			</a>
			</p>",
	),
	array(
		"name" => "neutrality-extractions-enwiki.7z",
		"link" => "neutrality-extractions-enwiki.7z",
		"size" => "244 MB",
		"desc" => "<p>This dataset contains a historical roundup of articles in <strong>English language</strong> that contained the template pointing out a lack of neutrality and wasn't reset for at least seven days after improvement. </p><p>Two versions of the article have been extracted: the one containing the neutrality template and the one in which the lack of neutrality has obviously been resolved.</p>",
	),
	array(
		"name" => "neutrality-extractions-dewiki.7z",
		"link" => "neutrality-extractions-dewiki.7z",
		"size" => "30 MB",
		"desc" => "<p>This dataset contains a historical roundup of articles in <strong>German language</strong> that contained the template pointing out a lack of neutrality and wasn't reset for at least seven days after improvement.</p><p>Two versions of the article have been extracted: the one containing the neutrality template and the one in which the lack of neutrality has obviously been resolved.</p>",
	),
);

