<?php

$Headline = "RENDER-Toolkit";
$Introduction = "Hi and welcome on the RENDER Toolkit Page.";

$Text1 = "Here you can try the tools that are developed within the <a href=\"http://render-project.eu/\">RENDER project</a>. An encyclopedic, neutral text is requested in Wikipedia Articles. The purpose of the RENDER Toolkit is to detect articles with a lack of diversity. That means the tools search for articles missing facts or being biased due to an unbalanced representation of viewpoints.";

 
$Text2 = "The tools cannot give a final answer to the question whether an article is incomplete or biased. There will be hints given that an analyzed text should be checked by human assessment. Thanks to computed checks of content it is possible to save time and to find out about issues of diversity which could not have been identified manually.  Now you as an editor can use your time for adding information or applying corrections to Wikipedia, instead of manually searching for diversity issues.";

$Text3 = "The tools are partly still at a development state. Therefore we are happy to receive comments by email (<a href=\"mailto:render@wikimedia.de\">render@wikimedia.de</a>) that help us improving the tools.";


?>
