<?php

$Headline = "RENDER-Toolkit";
$Introduction = "Hi and welcome on the RENDER Toolkit Page!";

$Text1 = "Here you can test and play with different tools. These are developed in the context of the research project RENDER (Reflecting Knowledge Diversity). In this project, Wikimedia Deutschland is a use case partner. </br> The tools provide an insight into the different analyses of diversity in Wikipedia, which are implemented within the project. For more Information about the project, please visit <a href=http://de.wikipedia.org/wiki/Wikipedia:RENDER>RENDER in Wikipedia</a> or <a href=http://render-project.eu>the project website</a>.";

$Text2 = "The whole toolkit as well as the tools are in a continuous process of development. We are looking forward to receiving suggestions, feedback or ideas on the <a href=http://de.wikipedia.org/wiki/Wikipedia_Diskussion:RENDER>discussion concerning RENDER in Wikipedia</a> or by <a href=mailto:render@wikimedia.de>email</a>.";

$Text3 = "";


?>
