<?php

$Headline = "RENDER-Toolkit";
$Introduction = "Hi and welcome on the RENDER Toolkit Page!";

$Text1 = "Here you can test and play with different tools. We develope the tools as part of the RENDER (Reflecting Knowledge Diversity) research project. Wikimedia Deutschland takes part as a use case partner in the RENDER project. The tools provide an insight into the different kinds of analyses of diversity, as they will be implemented. For more information about the project, please visit <a href=http://de.wikipedia.org/wiki/Wikipedia:RENDER>RENDER in Wikipedia</a> or <a href=http://render-project.eu>the project website</a>.";

$Text2 = "The tools and the toolkit itself are in a continuous process of development. We are happy to receive suggestions, feedback or ideas on the <a href=http://de.wikipedia.org/wiki/Wikipedia_Diskussion:RENDER>discussion concerning RENDER in Wikipedia</a> or by <a href=mailto:render@wikimedia.de>email</a>.";

$Text3 = "";


?>
