<?php
$Headline = "Imprint";
$Introduction = "This website is hosted by Wikimedia Deutschland e. V.:";

$Adress = array(
	"Title" => "Wikimedia Deutschland - Gesellschaft zur Förderung Freien Wissens e. V.",
	"Postbox" => "Postbox 30 32 43",
	"Zip" => "10729 Berlin",
	"Phone" => "Landline: +49(0)30-21915826-0",
	"Fax" => "Fax: +49(0)30-21915826-9",
	"Email" => "E-mail: <a href='mailto:info@wikimedia.de'>info@wikimedia.de</a>"
);

$Disclaimer = array(
	"Head" => "Disclaimer",
	"Text1" => "All services on this side are offered by Wikimedia Deutschland 
		as partner of the RENDER project. All rights are either at Wikimedia 
		Deutschland or at one of the other partners in the RENDER project. 
		Unless otherwise stated, all data on this page is licensed under 
		<a href='http://creativecommons.org/licenses/by-sa/3.0/deed.en'>Creative 
		Commons Attribution-Share-Alike License 3.0</a>.",
	"Text2" => "This software is not released as a product. It was written 
		primarily for Wikimedia Deutschland's own use, and is made public as is, 
		in the hope it may be useful. Wikimedia Deutschland may at any time 
		discontinue developing or supporting this software. There is no guarantee 
		any new versions or even fixes for security issues will be released."
);