<?php
$Headline = "Change Detector";
$Introduction = "Change Detector shows high editing activity in Wikipedia on a certain day and compares Wikipedias in different language versions. It enables the user to identify outdated articles in certain languages. The results are presented as a table. If a certain article was modified in almost every language version, but one or two languages were left out, you would be advised to have a closer look at the article. It could be outdated. ";

$Settings["Headline"] = "Settings";
$Settings["Text"] = "";

$Results["Headline"] = "Results";
$Results["Text"] = "";

$Uses["Headline"] ="Uses";
$Uses["Text"] = "";

$Languages["Headline"] = "Supported languages";
$Languages["Text"] = "<p>Change Detector analyses Wikipedia in the following languages:
</p>
<ul><li> English (en)
</li><li> French (fr)
</li><li> German (de)
</li><li> Portuguese (pt)
</li><li> Italian (it)
</li><li> Russian (ru)
</li><li> Dutch (nl)
</li><li> Polish (pl) 
</li><li> Swedish (sv)
</li><li> Spanish (es)
</li><li> Chinese (zh) (World only)
</li><li> Japanese (ja) (World only)
</li></ul>
";

$Lizenz = "<h2>Lizenz</h2>
<p>ChangeDetector is distributed under <a href=\"http://en.wikipedia.org/wiki/BSD_licenses\">BSD license</a>.</p>

 <code>
  <p>Copyright (c) 2012, Wikimedia Deutschland (Anselm Metzger)
  All rights reserved.</p>
 
  </p>Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:</p>
  <ul>
      <li>Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer. </li>
      <li>Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution. </li>
      <li>Neither the name of Wikimedia Deutschland nor the
        names of its contributors may be used to endorse or promote products
        derived from this software without specific prior written permission. </li>
  </ul>
 
  <p>THIS SOFTWARE IS PROVIDED BY WIKIMEDIA DEUTSCHLAND ''AS IS'' AND ANY
  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL WIKIMEDIA DEUTSCHLAND BE LIABLE FOR ANY
  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</p></code>

<h2>Disclaimer</h2>

  <code><p>NOTE: This software is not released as a product. It was written primarily for
  Wikimedia Deutschland's own use, and is made public as is, in the hope it may
  be useful. Wikimedia Deutschland may at any time discontinue developing or
  supporting this software. There is no guarantee any new versions or even fixes
  for security issues will be released.</p></code>";

?>
