<?php
$Headline = "Wikipedia Map Interface";
$Description = "Wikipedia Map is a showcase which visualizes all geo-tagged articles in the Wikipedia. Each geo-tagged article is marked at the corresponding coordinate. Out of it a world map of geo-tags emerges.";

$MoreInfo = "More Information";

$Languages["English"] = "English";
$Languages["Catalan"] = "Catalan";
$Languages["Spanish"] = "Spanish";
$Languages["Portuguese"] = "Portuguese";
$Languages["French"] = "French";
$Languages["Italian"] = "Italian";
$Languages["Greek"] = "Greek";
$Languages["Hebrew"] = "Hebrew";
$Languages["Croatian"] = "Croatian";
$Languages["Turkish"] = "Turkish";
$Languages["Russian"] = "Russian";
$Languages["Chinese"] = "Chinese";

$DynamicMap["Headline"] = "Dynamic Map";
$DynamicMap["Text"] = "The dynamic map is completely created in your browser. This has the
advantage that the map is interactive, you can zoom into it, change
colors, and see for every point what article it is and link to it. But
it has the major disadvantage that it requires some heavy resources. <strong>This
link may crash your browser.</strong> Use a reasonably fast machine,
a current version of Chrome, and be patient while loading the data
&mdash; your browser is loading more than 50 MB of data and processing
it via JavaScript into an HTML5 Canvas. By the way, you can locally
safe and open that page in order to have the map interface with you
without having to load it every time."
?>
