<?php
$Headline = "Wikipedia Map";
$Introduction = "The Wikipedia Map is basically a visualization of geo-tagged articles in Wikipedia. Each geo-tagged article is identified by a marking at the corresponding coordinates, compiling in the aggregate a world map of geotags. ";


$Settings["Headline"] = "Settings";
$Settings["Text"] = "You can choose the language version. Using the dynamic map, it is also possible to zoom and to click on a certain article. ";

$Results["Headline"] = "Results";
$Results["Text"] = "The underlying data is extracted from DBpedia, which is derived from Wikipedia, separate for each supported language. It provides static generated images as well as a dynamic version that allows navigating and zooming. The Wikipedia Map is a pure visualization tool. ";

$Uses["Headline"] = "Use";
$Uses["Text"] = "Wikipedia Map provides a valuable source of information about diversity in Wikipedia. On the one hand obvious data errors are revealed, e.g. many French articles are grouped at the zero meridian. On the other hand language specific biases become visible, e.g. the Catalan Wikipedia covers in-depth Catalonia in Spain, covers several parts of Europe as well as the USA, but provides only weak coverage of other parts of the world. Future improvements of the Wikipedia Map Interface will first emerge efforts by Wikimedia on better support for geographical information extraction.";



?>
